### ISSUE TITLE
iOS Build

### ISSUE THREAD

**Issue by JacksonUtsch** [rhx/SwiftGLib#4]
Is a port to iOS possible with glib? A compiled .framework would be the goal here.

**Comment by rhx** [comment]
This is probably going to be challenging: [it appears that people have been able to cross-compile GLib for iOS](https://stackoverflow.com/questions/17638594/how-to-build-glib-for-ios#17733328).  As long as you use the same version of GLib as you have on your Mac, you can try running `run-gir2swift.sh` and then use the generated code in the package for cross-compiling.
