### ISSUE TITLE
Regression: Can no longer iterate over a ListRef using for-in loop

### ISSUE THREAD

**Issue by jasaldivara** [rhx/SwiftGLib#6]
I have some code which was working previously, where I iterated over a ListRef in a for-in loop, but it stopped working when I upgraded my system from Fedora 37 to 38.

ListRef was conforming to the Sequence protocol, and that was very convenient, but it seems not the case since I upgraded my Operating System.

This is a minimal code example that emits an error message on Fedora 38, but it still works OK on Fedora 37:

```
func iterateList(list: ListRef){
    for item in list {
        print ("item")
    }
}
```
This is the error message I get when I try to build the project:
```
error: for-in loop requires 'ListRef' to conform to 'Sequence'
    for item in list {
                ^~~~
```

I have two computers, one with Fedora 37 (x86-64) and the other one with Fedora 38 (aarch64). This bug is only present on the one with Fedora 38.

I'm using swift-lang package from Fedora repos in both machines. swift-lang version is 5.8.

The difference seems to be the glib2 package, which is version 2.76 on Fedora 38, while Fedora 37 have version 2.74.

**Comment by jasaldivara** [comment]
The reason why I'm using a `Glib.ListRef` is because I'm on Gtk3, iterating over the `selectedItems` of an `IconView`, and the `getSelectedRows()` of a `GtkTreeSelection`. Both of them return a `ListRef` representing a list of `TreePath` objects.

After some digging on the latest commits, I found out `Glib.ListRef` was replaced with a typed variant: `TypedListRef`. `ListRef` still exists as generated code, but it does not longer conform to the `Sequence` protocol, while the new one `TypedListRef` does conform to the protocol.

After that, now I'm using `IconView.selectedItems: ListRef` to create a `TypedListRef<TreePath>`. This is how my code looks now:

```
myIconView.onSelectionChanged { (unownedSelf: IconViewRef) in
    print ("Change in selection")

    if let selectedItems = unownedSelf.selectedItems {

        let typedSelectedItems = TypedListRef<TreePath>(selectedItems)

        print ("Before the loop")

        for path in typedSelectedItems {
        
            print("Inside the loop")
            
            // (More code here...)
        }
    }
}
```

Now, my code compiles correctly, without any error messages, but I'm having a new problem: The program crashes when i'm iterating over the `TypedListRef`:

```
Change in selection
Before the loop
fish: Job 1, 'swift run MySwiftProgram' terminated by signal SIGSEGV (Address boundary error)
```

I think the crash happens in the `for path in typedSelectedItems {` line, because the previous message is printed to the terminal, but the inside `print` statement does not get executed.

**Comment by rhx** [comment]
You are on the right track with `TypedListRef`.  However, `TypeList*` is for primitive types (such as `CInt`), but your list is tracking a reference to another GTK object (a `TreePath`), what you probably want here is something along the following lines:

```Swift
myIconView.onSelectionChanged { (unownedSelf: IconViewRef) in
    print ("Change in selection")

    if let selectedItems = unownedSelf.selectedItems {

        let typedSelectedItems = ReferenceListRef<TreePathRef>(selectedItems)

        print ("Before the loop")

        for path in typedSelectedItems {
        
            print("Inside the loop")
            
            // (More code here...)
        }
    }
}
```

Could you let me know if this works for you?

**Comment by jasaldivara** [comment]
Yes, using `ReferenceListRef<TreePathRef>` instead of `TypedListRef<TreePath>` solved my problem.

Thanks!
