### ISSUE TITLE
Building on Fedora 39 fails: GLib.swift:386:74: error: cannot find type 'utimbuf' in scope

### ISSUE THREAD

**Issue by brunophilipe** [rhx/SwiftGLib#7]
I've attempted both using `gtk3-devel` and `gtk4-devel`, but no dice. 

As a last resort I also attempted installing all developer packages, but that didn't help either.
```
$ sudo dnf group install "C Development Tools and Libraries" "Development Tools"
```

Swift is version 5.8.1:
 ```
$ swift --version
Swift version 5.8.1 (swift-5.8.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```

Here's my `Package.swift`:
[Package.swift.txt](https://github.com/rhx/SwiftGLib/files/15050943/Package.swift.txt)

Here's the full log:
[buildlog.txt](https://github.com/rhx/SwiftGLib/files/15050928/buildlog.txt)

**Comment by rhx** [comment]
Can you try again, please, and let me know if you are still having the issue?

If you are building a dependent package such as SwiftGtk, don't forget to run
```
swift package purge-cache
swift package update
```
prior to re-compiling.

**Comment by brunophilipe** [comment]
I can confirm the build completes successfully now. Thanks!
